config/routes.rb
Rails.application.routes.draw do
  devise_for :customers

  resources :customers, only: [:show, :edit, :update]
  
  root to: "items#index"
  
  resources :items do
    resources :orders, only: [:index, :create]
    collection do
      get 'search'
    end
  end

  post 'favorite/:id' => 'favorites#create', as: 'create_favorite'
  delete 'favorite/:id' => 'favorites#destroy', as: 'destroy_favorite'
  
  resources :products, only: [:index, :show] do
    resources :comments, only: :create
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: 'トップス'},
    { id: 3, name: 'アウター'},
    { id: 4, name: 'パンツ'},
    { id: 5, name: 'ワンピース'},
    { id: 6, name: 'シャツ・ブラウス'},
    { id: 7, name: 'コート'},
    { id: 8, name: 'シューズ'},
    { id: 9, name: 'アクセサリー'}
  ]

  include ActiveHash::Associations
  has_many :items
end

app/models/color.rb
class Color < ActiveHash::Base
  self.data = [
    { id: 1, name: 'レッド' },
    { id: 2, name: 'オレンジ' },
    { id: 3, name: 'イエロー' },
    { id: 4, name: 'ベージュ' },
    { id: 5, name: 'ブラウン' },
    { id: 6, name: 'グリーン' },
    { id: 7, name: 'カーキ' },
    { id: 8, name: 'ブルー' },
    { id: 9, name: 'ネイビー' },
    { id: 10, name: 'パープル' },
    { id: 11, name: 'ホワイト' },
    { id: 12, name: 'ブラック' },
    { id: 13, name: 'シルバー' },
    { id: 14, name: 'ゴールド' }
  ]

  include ActiveHash::Associations
  has_many :items
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :customer
  belongs_to :product
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders
  has_many :comments
  has_many :favorites, dependent: :destroy

  with_options presence: true do
    validates :nickname
    VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
    validates :password, format: { with: VALID_PASSWORD_REGEX, message: 'Include both letters and numbers' }, on: :create
    validates :last_name, format: { with: /\A[ぁ-んァ-ヶ一-龥々ー]+\z/ }
    validates :first_name, format: { with: /\A[ぁ-んァ-ヶ一-龥々ー]+\z/ }
    validates :last_name_kana, format: { with: /\A[ァ-ヶー－]+\z/ }
    validates :first_name_kana, format: { with: /\A[ァ-ヶー－]+\z/ }
    validates :birthday
  end

  def favorite_find(item_id)
    favorites.where(item_id: item_id).exists?
  end
end

app/models/destination.rb
class Destination < ApplicationRecord
  belongs_to :order

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :prefecture
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :customer
  belongs_to :item
end

app/models/item.rb
class Item < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  
  # テーブルアソシエーション
  has_one :order
  has_many :favorites, dependent: :destroy

  # アクティブハッシュアソシエーション
  belongs_to :category
  belongs_to :color
  belongs_to :size

  #アクティブストレージ
  has_one_attached :image

  with_options presence: true do
    validates :image
    validates :name
    validates :description
    validates :category_id
    validates :color_id
    validates :size_id
    validates :price
  end

  with_options numericality: { other_than: 1 } do
    validates :category_id
    validates :color_id
    validates :size_id
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  belongs_to :item
  has_one :destination
end

app/models/order_destination.rb
class OrderDestination

  include ActiveModel::Model
  attr_accessor :customer_id, :item_id, :postcode, :prefecture_id, :city, :block, :building, :phone_number, :token

  with_options presence: true do
    validates :customer_id
    validates :item_id
    validates :postcode, format: { with: /\A[0-9]{3}-[0-9]{4}\z/, message: 'is Invalid. Include hyphen(-)'}
    validates :prefecture_id, numericality: { other_than: 1, message: "can't be blank" }
    validates :city
    validates :block
    validates :phone_number, format: { with: /\A\d{10,11}\z/, message: 'is invalid'}
    validates :token
  end

  def save
    order = Order.create(customer_id: customer_id, item_id: item_id)
    Destination.create(postcode: postcode, prefecture_id: prefecture_id, city: city, block: block, building: building, phone_number: phone_number, order_id: order.id)
  end
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' }, { id: 2, name: '北海道' }, { id: 3, name: '青森県' },
    { id: 4, name: '岩手県' }, { id: 5, name: '宮城県' }, { id: 6, name: '秋田県' },
    { id: 7, name: '山形県' }, { id: 8, name: '福島県' }, { id: 9, name: '茨城県' },
    { id: 10, name: '栃木県' }, { id: 11, name: '群馬県' }, { id: 12, name: '埼玉県' },
    { id: 13, name: '千葉県' }, { id: 14, name: '東京都' }, { id: 15, name: '神奈川県' },
    { id: 16, name: '新潟県' }, { id: 17, name: '富山県' }, { id: 18, name: '石川県' },
    { id: 19, name: '福井県' }, { id: 20, name: '山梨県' }, { id: 21, name: '長野県' },
    { id: 22, name: '岐阜県' }, { id: 23, name: '静岡県' }, { id: 24, name: '愛知県' },
    { id: 25, name: '三重県' }, { id: 26, name: '滋賀県' }, { id: 27, name: '京都府' },
    { id: 28, name: '大阪府' }, { id: 29, name: '兵庫県' }, { id: 30, name: '奈良県' },
    { id: 31, name: '和歌山県' }, { id: 32, name: '鳥取県' }, { id: 33, name: '島根県' },
    { id: 34, name: '岡山県' }, { id: 35, name: '広島県' }, { id: 36, name: '山口県' },
    { id: 37, name: '徳島県' }, { id: 38, name: '香川県' }, { id: 39, name: '愛媛県' },
    { id: 40, name: '高知県' }, { id: 41, name: '福岡県' }, { id: 42, name: '佐賀県' },
    { id: 43, name: '長崎県' }, { id: 44, name: '熊本県' }, { id: 45, name: '大分県' },
    { id: 46, name: '宮崎県' }, { id: 47, name: '鹿児島県' }, { id: 48, name: '沖縄県' }
  ]

  include ActiveHash::Associations
  has_many :destinations
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :comments

  has_one_attached :image

  with_options presence: true do
    validates :name
    validates :description
  end
end

app/models/quantity.rb
class Quantity <ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: 1},
    { id: 3, name: 2},
    { id: 4, name: 3},
    { id: 5, name: 4},
    { id: 6, name: 5},
    { id: 7, name: 6},
    { id: 8, name: 7},
    { id: 9, name: 8},
    { id: 10, name: 9}
  ]

  include ActiveHash::Associations
  has_many :orders
end

app/models/size.rb
class Size < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: 'S' },
    { id: 3, name: 'M' },
    { id: 4, name: 'L' },
    { id: 5, name: 'F' }
  ]

  include ActiveHash::Associations
  has_many :items
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>MYBRND</title>
  <%= csrf_meta_tags %> 
  <%= csp_meta_tag %>
  <script type="text/javascript" src="https://js.pay.jp/v1/"></script>
  <%= stylesheet_link_tag 'application', media: 'all'%>
  <%= javascript_pack_tag 'application' %>
</head>

<body>
  <%= breadcrumbs separetor: " &rsaquo; " %>
  <%= yield %>
</body>

</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<%# 下部広告部分 %>
<div class='ad-footer-contents'>
  <h2 class='ad-footer-title'>
    今すぐ無料ダウンロード！
  </h2>
  <div class='store-btn'>
    <%= link_to image_tag("app-store.svg", class:"apple-btn"), "#" %>
    <%= link_to image_tag("google-play.png", class:"google-btn"), "#" %>
  </div>
</div>

<%# 会社概要 %>
<div class='footer'>
  <div class='footer-contents'>
    <div class='mybrand-details'>
      <h2 class='footer-content-head'>MYBRANDについて</h2>
      <ul>
        <li><%= link_to '会社概要（運営会社)', "#", class: "footer-link" %></li>
        <li><%= link_to 'プライバシーポリシー', "#", class: "footer-link" %></li>
        <li><%= link_to '利用規約', "#", class: "footer-link" %></li>
        <li><%= link_to 'ポイントに関する特約', "#", class: "footer-link" %></li>
      </ul>
    </div>
    <div class='mybrand-details'>
      <h2 class='footer-content-head'>MYBRANDを見る</h2>
      <ul>
        <li><%= link_to 'カテゴリー一覧', "#", class: "footer-link" %></li>
      </ul>
    </div>
    <div class='mybrand-details'>
      <h2 class='footer-content-head'>MYBRANDについて</h2>
      <ul>
        <li><%= link_to 'お知らせ', "#", class: "footer-link" %></li>
      </ul>
    </div>
  </div>
  <%= link_to 'MYBRAND', root_path, class:"footer-brand-logo" %>
</div>

app/views/shared/_header.html.erb
<%# CSS・・・assets/stylesheets/shared/header.css %>
<header class='top-page-header'>
  <div class='search-bar-contents'>
    <%= link_to "MYBRAND", root_path, class:"brand-logo" %>
    <%= search_form_for Item.ransack(params[:q]), url: search_items_path, html: {class: "search-form"} do |f|%>
      <%= f.text_field :name, placeholder: 'キーワードから探す', class: 'input-box' %>
      <br>
      <%= f.label :submit, class: "search-button" do %>
        <%= image_tag "search.png", class: "search-icon" %>
        <%= f.submit :submit, id: "q_submit", style: "display: none;" %>
      <% end %>
    <% end %>
  </div>
  <div class='nav'>
    <ul class='lists-left'>
      <li><%= link_to '商品検索', search_items_path, class: "item-search" %></li>
    </ul>
    <ul class='lists-right'>
      <% if customer_signed_in? %>
        <li><%= link_to current_customer.nickname, customer_path(current_customer.id), class: "customer-nickname" %></li>
        <li><%= link_to 'ログアウト', destroy_customer_session_path, method: :delete, class: "logout" %></li>
      <% else %>
        <li><%= link_to 'ログイン', new_customer_session_path, class: "login" %></li>
        <li><%= link_to '新規登録', new_customer_registration_path, class: "sign-up" %></li>
      <% end %>
    </ul>
  </div>
</header>

app/views/shared/_second-footer.html.erb
<footer class='second-fotter'>
  <div class='second-fotter-text-wrap'>
    <p class='second-fotter-text'>プライバシーポリシー</p>
  </div>
  <%= link_to "MYBRAND", root_path, class:"second-fotter-logo"%>
</footer>

app/views/shared/_second-header.html.erb
<header class='second-header'>
  <%= link_to "MYBRAND", root_path, class:"second-logo" %>
</header>