config/routes.rb
Rails.application.routes.draw do
  devise_for :customers

  resources :customers, only: [:show, :edit, :update]
  
  root to: "items#index"
  
  resources :items do
    resources :orders, only: [:index, :create]
    collection do
      get 'search'
    end
  end

  post 'favorite/:id' => 'favorites#create', as: 'create_favorite'
  delete 'favorite/:id' => 'favorites#destroy', as: 'destroy_favorite'
  
  resources :products, only: [:index, :show] do
    resources :comments, only: :create
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders
  has_many :comments
  has_many :favorites, dependent: :destroy

  with_options presence: true do
    validates :nickname
    VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
    validates :password, format: { with: VALID_PASSWORD_REGEX, message: 'Include both letters and numbers' }, on: :create
    validates :last_name, format: { with: /\A[ぁ-んァ-ヶ一-龥々ー]+\z/ }
    validates :first_name, format: { with: /\A[ぁ-んァ-ヶ一-龥々ー]+\z/ }
    validates :last_name_kana, format: { with: /\A[ァ-ヶー－]+\z/ }
    validates :first_name_kana, format: { with: /\A[ァ-ヶー－]+\z/ }
    validates :birthday
  end

  def favorite_find(item_id)
    favorites.where(item_id: item_id).exists?
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :authenticate_customer!

  def show
    @favorites = Favorite.where(customer_id: current_customer.id)
  end

  def edit
  end

  def update
    if current_customer.update(customer_params)
      bypass_sign_in(current_customer)
      redirect_to customer_path(current_customer.id)
    else
      render :edit
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:nickname, :email, :last_name, :first_name, :last_name_kana, :first_name_kana, :birthday)
  end

end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/edit.html.erb
<%= render "shared/second-header"%>

<%= form_with model: current_customer, url: customer_path, class: 'registration-main', local: true do |f| %>

<div class='form-wrap'>
  <div class='form-header'>
    <h1 class='form-header-text'>
      会員情報変更入力
    </h1>
  </div>

  <%= render 'shared/error_messages', model: f.object %>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">ニックネーム</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_area :nickname, class:"input-default", id:"nickname", maxlength:"40" %>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">メールアドレス</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.email_field :email, class:"input-default", id:"email", autofocus: true %>
  </div>
  
  <div class="form-group">
    <p class='form-info-header'>
      本人情報変更
    </p>
    <p class='form-info-text'>
      他のお客さまに公開されることはありません。
    </p>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">お名前(全角)</label>
      <span class="indispensable">必須</span>
    </div>
    <div class='input-name-wrap'>
      <%= f.text_area :last_name, class:"input-name", id:"last-name", placeholder:"例) 山田" %>
      <%= f.text_area :first_name, class:"input-name", id:"first-name", placeholder:"例) 陸太郎" %>
    </div>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">お名前カナ(全角)</label>
      <span class="indispensable">必須</span>
    </div>
    <div class='input-name-wrap'>
      <%= f.text_area :last_name_kana, class:"input-name", id:"last-name-kana", placeholder:"例) ヤマダ" %>
      <%= f.text_area :first_name_kana, class:"input-name", id:"first-name-kana", placeholder:"例) リクタロウ" %>
    </div>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">生年月日</label>
      <span class="indispensable">必須</span>
    </div>
    <div class='input-birth-wrap'>
      <%= raw sprintf(
                  f.date_select(
                    :birthday,
                    class:'select-birth',
                    id:"birth-date",
                    use_month_numbers: true,
                    prompt:'--',
                    start_year: 1930,
                    end_year: (Time.now.year - 5),
                    date_separator: '%s'),
                  "<p> 年 </p>", "<p> 月 </p>") + "<p> 日 </p>" %>
    </div>
    <p class='info-text'>※ 変更する情報は正しく入力してください。変更後の修正にはお時間を頂く場合があります。</p>
  </div>
  <div class='edit-btn'>
    <%= f.submit "変更する" ,class:"edit-red-btn" %>
  </div>
</div>
<% end %>

<%= render "shared/second-footer"%>

app/views/customers/show.html.erb
<%# header %>
<%= render "shared/second-header" %>

<%# マイページ %>
<div class="my-contents">
  <h2 class="title">MY PAGE</h2>
  <div class="customer-name">
    <%= current_customer.nickname %>
  </div>
  <h2 class="title">FAVORITE ITEM</h2>
  <ul class="my-item-lists">
  <% @favorites.each do |favorite| %>
    <li class="list">
      <%= link_to item_path(favorite.item_id) do %>
      <div class="item-img-content">
        <%= image_tag favorite.item.image, class:"my-item-img" %>
      </div>
      <div class="my-item-info">
        <h3 class="my-item-name">
          <%= favorite.item.name %>
        </h3>
        <div class="my-item-price">
          <span><%= favorite.item.price %>円</span>
        </div>
      </div>
      <% end %>
    </li>
  <% end %>
  </ul>
  <%= link_to "会員情報の変更", edit_customer_path(current_customer.id), class:"edit-btn" %>
</div>
<%# hooter %>
<%= render 'shared/second-footer' %>