config/routes.rb
Rails.application.routes.draw do
  devise_for :customers

  resources :customers, only: [:show, :edit, :update]
  
  root to: "items#index"
  
  resources :items do
    resources :orders, only: [:index, :create]
    collection do
      get 'search'
    end
  end

  post 'favorite/:id' => 'favorites#create', as: 'create_favorite'
  delete 'favorite/:id' => 'favorites#destroy', as: 'destroy_favorite'
  
  resources :products, only: [:index, :show] do
    resources :comments, only: :create
  end
end

app/models/item.rb
class Item < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  
  # テーブルアソシエーション
  has_one :order
  has_many :favorites, dependent: :destroy

  # アクティブハッシュアソシエーション
  belongs_to :category
  belongs_to :color
  belongs_to :size

  #アクティブストレージ
  has_one_attached :image

  with_options presence: true do
    validates :image
    validates :name
    validates :description
    validates :category_id
    validates :color_id
    validates :size_id
    validates :price
  end

  with_options numericality: { other_than: 1 } do
    validates :category_id
    validates :color_id
    validates :size_id
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    @items = Item.order('created_at DESC')
  end

  def show
    @item = Item.find(params[:id])
  end

  def search
    if params[:q]&.dig(:name)
      squished_keywords = params[:q][:name].squish
      params[:q][:name_cont_any] = squished_keywords.split(" ")
    end
    @q = Item.ransack(params[:q])
    @items = @q.result
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/index.html.erb
<%# header %>

<% breadcrumb :root %>

<%= render "shared/header" %>

<div class='main'>
  
  <%# ブランドロゴ%>
  <div class='title-contents'>
    <h2 class='brand-title'>
      MYBRAND
    </h2>
  </div>


  <%# 新着商品 %>
  <div class='new-arrival-contents'>
    <h2 class='title'>
      NEW ITEMS
    </h2> 
    <ul class='new-arrival-lists'>
      <li class='list'>
        <%= link_to "#" do%>
        <%= image_tag "sample3.jpg", class:"list-pict" %>
        <h3 class='list-text'>
          リング
        </h3>
        <% end %>
      </li>
      <li class='list'>
        <%= link_to "#" do %>
        <%= image_tag "sample2.jpg", class:"list-pict" %>
        <h3 class='list-text'>
          ジーンズ
        </h3>
        <% end %>
      </li>
    </ul>
  </div>


  <%# 開発商品リンク %>
  <div class='product-nav'>
    <%= link_to products_path do %>
    <h2 class='product-title'>
      一緒に着てみたい服を作ってみませんか？
    </h2>
    <p class='product-text'>
      こんな服あったらいいのにな......
    </p>
    <p class='product-text'>
      こういうデザイン・カラーあったらもっといいはず.....
    </p>
    <p class='product-text'>
      そういったお声をぜひ聞かせてください！
    </p>
    <% end %>
  </div>


  <%# 商品一覧 %>
  <div class='item-contents'>
    <h2 class='title'>ITEMS</h2>
    
    <ul class='item-lists'>
    <% @items.each do |item| %>
      <li class='list'>
        <%= link_to item_path(item.id) do %>
        <div class='item-img-content'>
          <%= image_tag item.image, class: "item-img" %>
        </div>
        <div class='item-info'>
          <h3 class='item-name'>
            <%= item.name %>
          </h3>
          <div class='item-price'>
            <span><%= item.price %>円</span>
          </div>
        </div>
        <% end %>
      </li>
    <% end %>
    </ul>
  </div>
</div>

<%# hooter %>
<%= render "shared/footer" %>

app/views/items/search.html.erb
<%# header %>

<% breadcrumb :search %>

<%= render "shared/header" %>

<div class="main">

  <%# 検索表示 %>
  <h3>ITEM SEARCH</h3>

  <div class='item-contents' id="details-search-result-wrapper">
    <%= search_form_for @q, url: search_items_path, html: {id: "detailed-search-form"} do |f| %>
      <div class="search-field">
        <%= f.label :name, '商品名' %>
        <br>
        <%= f.text_field :name, placeholder: '商品名', value: params[:q]&.dig(:name) %>
      </div>
      <div class="search-field">
        <%= f.label :category_id_eq, 'カテゴリー' %>
        <br>
        <%= f.collection_check_boxes(:category_id_in, Category.all, :id, :name, {}) %>
      </div>
      <div class="search-field">
        <%= f.label :price_qteq, '価格' %>
        <br>
        <%= f.number_field :price_gteq %> 円以上
        <br>
        <%= f.number_field :price_lteq %> 円以下
      </div>
      <%= f.submit "検索" %>
    <% end %>

    <h2 class='title'>ITEMS</h2>
    
    <ul class='item-lists' id="deatailed-search-result">
      <% @items.each do |item| %>
        <li class='list'>
          <%= link_to item_path(item.id) do %>
            <div class='item-img-content'>
              <%= image_tag item.image, class: "item-img" %>
            </div>
            <div class='item-info'>
              <h3 class='item-name'>
                <%= item.name %>
              </h3>
              <div class='item-price'>
                <span><%= item.price %>円</span>
              </div>
            </div>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

<%# hooter %>
<%= render "shared/footer" %>

app/views/items/show.html.erb
<% breadcrumb :item %>

<%= render "shared/header" %>

<%# 商品の概要 %>
<div class="item-show">
  <div class="item-box">
    <h2 class="name">
      <%= @item.name %>
    </h2>
    <div class="item-img-content">
      <%= image_tag @item.image ,class:"item-box-img" %>
    <div class="item-price-text">
      <span class="item-price">
        ¥<%= @item.price %>
      </span>
    </div>

    <div class="item-explain-box">
      <span><%= @item.description %></span>
    </div>
    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-item">商品名</th>
          <td class="detail-value"><%= @item.name %></td>
        </tr>
        <tr>
          <th class="detail-item">カテゴリー</th>
          <td class="detail-value"><%= @item.category.name %></td>
        </tr>
        <tr>
          <th class="detail-item">カラー</th>
          <td class="detail-value"><%= @item.color.name %></td>
        </tr>
        <tr>
          <th class="detail-item">サイズ</th>
          <td class="detail-value"><%= @item.size.name %></td>
        </tr>
        <tr>
          <th class="detail-item">プライス</th>
          <td class="detail-value">¥<%= @item.price %></td>
        </tr>
      </tbody>
    </table>
    <div class="option">
      <div class="favorite-btn">
        <% if customer_signed_in? %>
          <% if current_customer.favorite_find(@item.id) %>
            <%= link_to "お気に入り解除", destroy_favorite_path(@item.id), method: :delete %> 
          <% else %>
            <%= link_to "お気に入り登録", create_favorite_path(@item.id), method: :post %>
          <% end %>
        <% end %>
      </div>
    </div>
    <%= link_to "購入する", item_orders_path(@item.id), class:"item-red-btn"%>
  </div>
  <a href="#" class="another-item"><%= @item.category.name %>をもっと見る</a>
</div>

<%= render "shared/footer" %>