config/routes.rb
Rails.application.routes.draw do
  devise_for :customers

  resources :customers, only: [:show, :edit, :update]
  
  root to: "items#index"
  
  resources :items do
    resources :orders, only: [:index, :create]
    collection do
      get 'search'
    end
  end

  post 'favorite/:id' => 'favorites#create', as: 'create_favorite'
  delete 'favorite/:id' => 'favorites#destroy', as: 'destroy_favorite'
  
  resources :products, only: [:index, :show] do
    resources :comments, only: :create
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: 'トップス'},
    { id: 3, name: 'アウター'},
    { id: 4, name: 'パンツ'},
    { id: 5, name: 'ワンピース'},
    { id: 6, name: 'シャツ・ブラウス'},
    { id: 7, name: 'コート'},
    { id: 8, name: 'シューズ'},
    { id: 9, name: 'アクセサリー'}
  ]

  include ActiveHash::Associations
  has_many :items
end

app/models/color.rb
class Color < ActiveHash::Base
  self.data = [
    { id: 1, name: 'レッド' },
    { id: 2, name: 'オレンジ' },
    { id: 3, name: 'イエロー' },
    { id: 4, name: 'ベージュ' },
    { id: 5, name: 'ブラウン' },
    { id: 6, name: 'グリーン' },
    { id: 7, name: 'カーキ' },
    { id: 8, name: 'ブルー' },
    { id: 9, name: 'ネイビー' },
    { id: 10, name: 'パープル' },
    { id: 11, name: 'ホワイト' },
    { id: 12, name: 'ブラック' },
    { id: 13, name: 'シルバー' },
    { id: 14, name: 'ゴールド' }
  ]

  include ActiveHash::Associations
  has_many :items
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :customer
  belongs_to :product
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders
  has_many :comments
  has_many :favorites, dependent: :destroy

  with_options presence: true do
    validates :nickname
    VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
    validates :password, format: { with: VALID_PASSWORD_REGEX, message: 'Include both letters and numbers' }, on: :create
    validates :last_name, format: { with: /\A[ぁ-んァ-ヶ一-龥々ー]+\z/ }
    validates :first_name, format: { with: /\A[ぁ-んァ-ヶ一-龥々ー]+\z/ }
    validates :last_name_kana, format: { with: /\A[ァ-ヶー－]+\z/ }
    validates :first_name_kana, format: { with: /\A[ァ-ヶー－]+\z/ }
    validates :birthday
  end

  def favorite_find(item_id)
    favorites.where(item_id: item_id).exists?
  end
end

app/models/destination.rb
class Destination < ApplicationRecord
  belongs_to :order

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :prefecture
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :customer
  belongs_to :item
end

app/models/item.rb
class Item < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  
  # テーブルアソシエーション
  has_one :order
  has_many :favorites, dependent: :destroy

  # アクティブハッシュアソシエーション
  belongs_to :category
  belongs_to :color
  belongs_to :size

  #アクティブストレージ
  has_one_attached :image

  with_options presence: true do
    validates :image
    validates :name
    validates :description
    validates :category_id
    validates :color_id
    validates :size_id
    validates :price
  end

  with_options numericality: { other_than: 1 } do
    validates :category_id
    validates :color_id
    validates :size_id
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  belongs_to :item
  has_one :destination
end

app/models/order_destination.rb
class OrderDestination

  include ActiveModel::Model
  attr_accessor :customer_id, :item_id, :postcode, :prefecture_id, :city, :block, :building, :phone_number, :token

  with_options presence: true do
    validates :customer_id
    validates :item_id
    validates :postcode, format: { with: /\A[0-9]{3}-[0-9]{4}\z/, message: 'is Invalid. Include hyphen(-)'}
    validates :prefecture_id, numericality: { other_than: 1, message: "can't be blank" }
    validates :city
    validates :block
    validates :phone_number, format: { with: /\A\d{10,11}\z/, message: 'is invalid'}
    validates :token
  end

  def save
    order = Order.create(customer_id: customer_id, item_id: item_id)
    Destination.create(postcode: postcode, prefecture_id: prefecture_id, city: city, block: block, building: building, phone_number: phone_number, order_id: order.id)
  end
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' }, { id: 2, name: '北海道' }, { id: 3, name: '青森県' },
    { id: 4, name: '岩手県' }, { id: 5, name: '宮城県' }, { id: 6, name: '秋田県' },
    { id: 7, name: '山形県' }, { id: 8, name: '福島県' }, { id: 9, name: '茨城県' },
    { id: 10, name: '栃木県' }, { id: 11, name: '群馬県' }, { id: 12, name: '埼玉県' },
    { id: 13, name: '千葉県' }, { id: 14, name: '東京都' }, { id: 15, name: '神奈川県' },
    { id: 16, name: '新潟県' }, { id: 17, name: '富山県' }, { id: 18, name: '石川県' },
    { id: 19, name: '福井県' }, { id: 20, name: '山梨県' }, { id: 21, name: '長野県' },
    { id: 22, name: '岐阜県' }, { id: 23, name: '静岡県' }, { id: 24, name: '愛知県' },
    { id: 25, name: '三重県' }, { id: 26, name: '滋賀県' }, { id: 27, name: '京都府' },
    { id: 28, name: '大阪府' }, { id: 29, name: '兵庫県' }, { id: 30, name: '奈良県' },
    { id: 31, name: '和歌山県' }, { id: 32, name: '鳥取県' }, { id: 33, name: '島根県' },
    { id: 34, name: '岡山県' }, { id: 35, name: '広島県' }, { id: 36, name: '山口県' },
    { id: 37, name: '徳島県' }, { id: 38, name: '香川県' }, { id: 39, name: '愛媛県' },
    { id: 40, name: '高知県' }, { id: 41, name: '福岡県' }, { id: 42, name: '佐賀県' },
    { id: 43, name: '長崎県' }, { id: 44, name: '熊本県' }, { id: 45, name: '大分県' },
    { id: 46, name: '宮崎県' }, { id: 47, name: '鹿児島県' }, { id: 48, name: '沖縄県' }
  ]

  include ActiveHash::Associations
  has_many :destinations
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :comments

  has_one_attached :image

  with_options presence: true do
    validates :name
    validates :description
  end
end

app/models/quantity.rb
class Quantity <ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: 1},
    { id: 3, name: 2},
    { id: 4, name: 3},
    { id: 5, name: 4},
    { id: 6, name: 5},
    { id: 7, name: 6},
    { id: 8, name: 7},
    { id: 9, name: 8},
    { id: 10, name: 9}
  ]

  include ActiveHash::Associations
  has_many :orders
end

app/models/size.rb
class Size < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: 'S' },
    { id: 3, name: 'M' },
    { id: 4, name: 'L' },
    { id: 5, name: 'F' }
  ]

  include ActiveHash::Associations
  has_many :items
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    @items = Item.order('created_at DESC')
  end

  def show
    @item = Item.find(params[:id])
  end

  def search
    if params[:q]&.dig(:name)
      squished_keywords = params[:q][:name].squish
      params[:q][:name_cont_any] = squished_keywords.split(" ")
    end
    @q = Item.ransack(params[:q])
    @items = @q.result
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_customer!
  before_action :item_data_read, only: [:index, :create]

  def index
    @order_destination = OrderDestination.new
  end

  def create
    @order_destination = OrderDestination.new(order_params)
    if @order_destination.valid?
      pay_item
      @order_destination.save
      redirect_to root_path
    else
      render :index
    end
  end

  private

  def item_data_read
    @item = Item.find(params[:item_id])
  end

  def order_params
    params.require(:order_destination).permit(:postcode, :prefecture_id, :city, :block, :building, :phone_number).merge(customer_id: current_customer.id, item_id: params[:item_id], token: params[:token])
  end

  def pay_item
    Payjp.api_key = ENV['PAYJP_SECRET_KEY']
    Payjp::Charge.create(
      amount: @item.price,
      card: order_params[:token],
      currency: 'jpy'
    )
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_customer!, only: [:show]

  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
    @comments = @product.comments.includes(:customer)
    @comment = Comment.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/index.html.erb
<%# header %>
<% breadcrumb :products%>

<%= render "shared/header" %>

<div class='main' >

  <%# ブランドロゴ%>
  <div class='title-contents'>
    <h2 class='brand-title'>
      MYBRAND
    </h2>
  </div>

  <%# 開発商品一覧 %>
  <div class='product-contents'>
    <h2 class='title'>PRODUCT ITEMS</h2>
    
    <ul class='product-lists'>
      <% @products.each do |product| %>
        <li class='list'>
          <%= link_to product_path(product.id) do %>
          <div class='product-img-content'>
            <%= image_tag product.image, class: "product-img" %>
          </div>
          <div class='product-info'>
            <h3 class='product-name'>
              <%= product.name %>
            </h3>
            <div class='product-description'>
              <span><%= product.description %></span>
            </div>
          </div>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

<%# hooter %>
<%= render "shared/footer" %>

app/views/products/show.html.erb
<% breadcrumb :product %>

<%= render "shared/header" %>

<%# 開発商品の概要 %>
<div class="product-show">
  <div class="product-box">
    <h2 class="name">
      <%= @product.name %>
    </h2>
    <div class="product-img-content">
      <%= image_tag @product.image ,class:"product-box-img" %>
    <div class="product-text">
      <span class="product-show-description">
        <%= @product.description %>
      </span>
    </div>
  </div>

  <%# コメント欄 %>
  <div class="comment-box">
    <% if customer_signed_in? %>
      <%= form_with model: [@product, @comment], id: "comment-form" do |f| %>
        <%= f.text_area :comment, class:"comment-text" %>
        <p class="comment-warn">
          相手のことを考え丁寧なコメントを心がけましょう。
          <br>
          不快な言葉遣いなどは利用制限や退会処分となることがあります。
        </p>
        <%= f.submit "コメントする", class:"comment-btn" %>
      <% end %>
    <% end %>
  </div>

  <%# コメント表示欄 %>
  <div id="comments" class="comments">
    <h4>＜コメント一覧＞</h4>
    <% @product.comments.each do |comment| %>
      <div class="comment">
        <div class="customer-info">
          <p class="customer-names"><%= comment.customer.nickname %> : </p>
          <div class="chatting">
            <div class="customer-comment">
              <p><%= comment.comment %></p>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

<%= render "shared/footer" %>